version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=lawfirm;Username=postgres;Password=postgres
      - Redis__Configuration=redis:6379
      - SmtpSettings__Host=mailhog
      - SmtpSettings__Port=1025
      - SmtpSettings__Username=
      - SmtpSettings__Password=
      - SmtpSettings__From=noreply@lawfirm.local
      - SmtpSettings__EnableSsl=false
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lawfirm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP

  superadmin:
    build:
      context: .
      dockerfile: LawFirm.SuperAdminPortal/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - redis
      - mailhog

volumes:
  pgdata: 